export const pageThemes: Record<string, "light" | "dark"> = {
  "/": "light",
  "/services": "dark",
  "/services/brand-identity": "light",
  "/services/brand-systems": "dark",
  "/services/digital-design": "light",
  "/services/marketing-assets": "light",
  "/services/print-and-environmental-design": "dark",
  "/solutions": "dark",
  "/solutions/merchandise-and-promotional-products": "light",
  "/solutions/company-stores": "dark",
  "/solutions/swag-storefronts": "light",
  "/solutions/on-demand-kits": "dark",
  "/solutions/print-and-environmental": "dark",
  "/blog": "light",
};
